# Generated by Django 4.0.3 on 2023-11-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('in_progress', '대여'), ('reserved', '예약')], default='reserved', max_length=20),
        ),
    ]
