# Generated by Django 4.0.3 on 2023-12-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_rental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('in_progress', '대여'), ('reserved', '예약'), ('returned', '반납')], default='reserved', max_length=20),
        ),
    ]
