# Generated by Django 4.2.7 on 2023-11-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('bank_account', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name': '임금',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '직원'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.wage'),
        ),
    ]
