# Generated by Django 4.2.7 on 2023-11-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_wage_alter_employee_options_remove_employee_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='phone_number',
            new_name='branch_phone_number',
        ),
    ]
