# Generated by Django 4.0.3 on 2023-11-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_phone_number_branch_branch_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
