# Generated by Django 4.0.3 on 2023-12-04 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='employee',
            name='wage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee.wage'),
        ),
    ]
