# Generated by Django 4.2.7 on 2023-11-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread', models.CharField(max_length=100, verbose_name='차량 브랜드')),
                ('size', models.CharField(choices=[('large', '대형'), ('small', '소형'), ('medium', '중형')], max_length=6, verbose_name='차량 크기')),
            ],
            options={
                'verbose_name': '차량 유형',
            },
        ),
    ]
