# Generated by Django 4.2.7 on 2023-11-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '차량 옵션',
            },
        ),
        migrations.RenameField(
            model_name='cartype',
            old_name='bread',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='cartype',
            name='size',
            field=models.CharField(choices=[('large', '대형'), ('medium', '중형'), ('small', '소형')], max_length=6, verbose_name='차량 크기'),
        ),
    ]
