# Generated by Django 4.2.7 on 2023-11-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_mileage_car_rental_price_alter_cartype_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('reason', models.TextField()),
                ('cost', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='car.car')),
            ],
            options={
                'verbose_name': '정비',
            },
        ),
    ]
