# Generated by Django 4.2.7 on 2023-11-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_car_branch_alter_cartype_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caroption',
            name='option_name',
        ),
        migrations.AddField(
            model_name='caroption',
            name='airconditioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caroption',
            name='blackbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caroption',
            name='heatedseat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caroption',
            name='navigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caroption',
            name='sunroof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='size',
            field=models.CharField(choices=[('small', '소형'), ('large', '대형'), ('medium', '중형')], max_length=6, verbose_name='차량 크기'),
        ),
    ]
