# Generated by Django 4.2.7 on 2023-11-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_cartype_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartype',
            name='size',
            field=models.CharField(choices=[('large', '대형'), ('medium', '중형'), ('small', '소형')], max_length=6, verbose_name='차량 크기'),
        ),
    ]
